### ISSUE TITLE
Reports failure if redeploying same docker image

### ISSUE THREAD

**Issue by RasmusWL** [issuu/sure-deploy#11]
If we made a change to the README, we will trigger a new deploy. The docker-image we want to deploy will not change. sure-deploy reports this as an error, but it would be nice for this to be allowed :smile: 

Example:
```
$ docker run --rm --mount type=bind,src=<docker-compose.yml>,dst=/home/opam/docker-compose.yml,readonly -e BUILD_NUMBER=50 issuu/sure-deploy:58 verify --host <host> --verbose <name>
Service '<name>' expected '<image>:50' but '<image>:49@sha256:<sha>' was deployed
```

**Comment by Leonidas-from-XIV** [comment]
Can you show me the YAML file? sure-deploy just tests what the YAML file states and it looks like the YAML file states there should be `'<image>:50'`.

**Comment by RasmusWL** [comment]
yes. It has `image: '<registry>/<image>:${BUILD_NUMBER}'` and the registry has this tag. 

I guess the `docker -H <swarm> stack deploy -c docker-compose.yml <image>`  command is "helpful" and doesn't actually change the image?

**Comment by Leonidas-from-XIV** [comment]
From what I see you specified `BUILD_NUMBER=50` so sure-deploy was looking for `<registry>/<image>:50` which I would consider proper behaviour, you were expecting image version `50` but what was deployed was `49`. Why `stack deploy` did not do that I don't know.

In fairness, I haven't encountered any such behaviour from `stack deploy` yet, even with changes that do not affect the image file we still get a new version in place.

**Comment by RasmusWL** [comment]
I found some [documentation](https://github.com/moby/moby/issues/29676) for docker stack deploy --compose-file, saying

> if the image uses a tag, the image's immutable identifier is resolved by querying the registry. This resolution takes place on the manager node that the service is created on.

So I guess docker stack deploy looks at the SHA for both 49 and 50, and realizing they are the same stops doing more.

There is an option called `--resolve-image`, which might be helpful, but I haven't really been able to figure it out :neutral_face:

**Comment by Leonidas-from-XIV** [comment]
I could make it check the SHA for both versions if the tag does not match, do you think this would be an appropriate solution to your problem? I would just need to figure out how to get the hash of `:50` in that case.

(I still think it is a very weird behaviour if you request `:50` to get you `:49`)

**Comment by RasmusWL** [comment]
Checking the SHA sounds like a solution yes :blush:
