### ISSUE TITLE
No registry auth handling

### ISSUE THREAD

**Issue by yangm97** [issuu/sure-deploy#19]
Hello, it appears that sure-deploy doesn't implement handling for registry authentication across nodes, i.e. an equivalent for `docker stack deploy --with-registry-auth`.

And, by extension, it will not check if all nodes were able to authenticate and fetch images.

**Comment by Leonidas-from-XIV** [comment]
Hi @yangm97, somehow I missed your message.

I'll take a look what is required to get that working!
