### ISSUE TITLE
Specify host and port

### ISSUE THREAD

**Issue by ebekebe** [issuu/sure-deploy#5]
I tried to run your tool on our remote swarm that is only reachable via a SSH tunnel to localhost:SOME_PORT. How can I specify the port? I tried `localhost:2340` and `tcp://localhost:2340` which failed with the following error:

```
(monitor.ml.Error
 ("Failed to resolve Uri"
  ((scheme http) (host localhost:2340) (port 2375)
   (path (/ v1.24 / services))
   (query
    ((filters ("{\"label\":{\"com.docker.stack.namespace=CD\":true}}"))))))
 ("Raised at file \"src/import0.ml\" (inlined), line 237, characters 22-32"
  "Called from file \"src/error.ml\" (inlined), line 9, characters 14-30"
  "Called from file \"src/or_error.ml\", line 72, characters 17-32"
  "Called from file \"src/deferred1.ml\", line 20, characters 40-45"
  "Called from file \"src/job_queue.ml\", line 159, characters 6-47"))
```

For reference, I used the docker image `leonidasfromxiv/sure-deploy:13`.

**Comment by Leonidas-from-XIV** [comment]
Sorry, I seem to have missed your post!

You should be able to set it via `--host localhost --port 2375` (at least in `sure-deploy:49`). You can find the options when you pass in the `--help` option to the subcomand you want to use, e.g. `verify --help`.

**Comment by Leonidas-from-XIV** [comment]
I'm closing this issue assuming this solves your problem but if you still have the problem feel free to reopen.
